# ----------- DECLARATION & JOBS ----------- #

stages:
  - build
  - test
  - deploy

# Declare a runner
.docker: &docker
  tags:
    - docker

# Master branch
.master: &master "master@development/abitech.nextapi"

# Run docker-container in runner with dotnet 6.0 image
.dotnet-job: &dotnet-job
  <<: *docker
  image: mcr.microsoft.com/dotnet/sdk:7.0

# ----------- END OF DECLARATION & JOBS SECTION ----------- #

# ----------- VARIABLES ----------- #

variables:
  VER: "2.0.0"
  VERSION: "$VER.$CI_PIPELINE_IID-abitech" # '-abitech' suffix required, cause our repository is fork.

# ----------- END OF VARIABLES SECTION ----------- #

# ----------- BUILD ----------- #

# Common Build stage
.distro: &distro
  stage: build
  <<: *dotnet-job
  only:
    - merge_requests
  script:
    - cd $projectFolder
    - dotnet build --configuration Release

# Build NextApi.Testing project
distro-testing:
  <<: *distro
  variables:
    projectFolder: src/base/NextApi.Testing

# Build NextApi.Common project
distro-common:
  <<: *distro
  variables:
    projectFolder: src/base/NextApi.Common

# Build NextApi.Server.Common project
distro-server-common:
  <<: *distro
  variables:
    projectFolder: src/base/NextApi.Server.Common

# Build NextApi.UploadQueue.Common project
distro-uploadqueue-common:
  <<: *distro
  variables:
    projectFolder: src/base/NextApi.UploadQueue.Common

# Build NextApi.Client project
distro-client:
  <<: *distro
  variables:
    projectFolder: src/client/NextApi.Client

# Build NextApi.Client.UploadQueue project
distro-client-uploadqueue:
  <<: *distro
  variables:
    projectFolder: src/client/NextApi.Client.UploadQueue

# Build NextApi.Client.Autofac project
distro-client-autofac:
  <<: *distro
  variables:
    projectFolder: src/client/NextApi.Client.Autofac

# Build NextApi.Client.MicrosoftDI project
distro-client-microsoft-di:
  <<: *distro
  variables:
    projectFolder: src/client/NextApi.Client.MicrosoftDI

# Build NextApi.Server project
distro-server:
  <<: *distro
  variables:
    projectFolder: src/server/NextApi.Server

# Build NextApi.Server.EfCore project
distro-server-efcore:
  <<: *distro
  variables:
    projectFolder: src/server/NextApi.Server.EfCore

# Build NextApi.Server.UploadQueue project
distro-server-uploadqueue:
  <<: *distro
  variables:
    projectFolder: src/server/NextApi.Server.UploadQueue


# ----------- END OF BUILD SECTION ----------- #

# ----------- TEST ----------- #

# Common Test stage
.dotnet-test: &dotnet-test
  stage: test
  <<: *dotnet-job
  only:
    - merge_requests
  script:
    - cd $projectFolder
    - dotnet test --verbosity normal --configuration Release

test-client:
  <<: *dotnet-test
  variables:
    projectFolder: test/NextApi.Client.Tests

test-server:
  <<: *dotnet-test
  variables:
    NEXTAPI_TESTDB_PORT: "3306"
    NEXTAPI_TESTDB_HOST: "blade1.abitech.kz"
    projectFolder: test/NextApi.Server.Tests

test-ef-core:
  <<: *dotnet-test
  variables:
    projectFolder: test/NextApi.Server.EfCore.Tests

# ----------- END OF TEST SECTION ----------- #

# ----------- NUGETIZE ----------- #

nuget-bridge:
  only:
    - *master
  stage: deploy
  trigger:
    include: nuget.gitlab-ci.yml

# ----------- END OF NUGETIZE SECTION ----------- #
